"use client";

import { useEffect, useRef, useState } from "react";
import { aiModes, type Mode } from "@/lib/data";

type Msg = {
  role: "user" | "ai";
  text: string;
  offer?: boolean; // show hint / full-solution chips
};

const DEMO_HINT =
  "💡 Hint: Look for two numbers that multiply to give the constant term and add to give the middle coefficient. Try listing factor pairs of 6 — which pair sums to 5? Tell me what you get and we'll finish it together.";

const DEMO_SOLUTION =
  "Here's the complete solution, step by step:\n\n1) Start with x² − 5x + 6 = 0.\n2) We need two numbers that multiply to +6 and add to −5 → they are −2 and −3.\n3) Factorise: (x − 2)(x − 3) = 0.\n4) A product is zero when either factor is zero: x − 2 = 0 or x − 3 = 0.\n\n✅ Roots: x = 2 and x = 3.\n\nQuick check: 2² − 5(2) + 6 = 0 ✓ and 3² − 5(3) + 6 = 0 ✓\n\nWant me to generate 3 similar practice questions?";

function aiReply(mode: Mode, userText: string): Msg {
  const t = userText.toLowerCase();
  if (t.includes("x²") || t.includes("x^2") || t.includes("solve")) {
    return {
      role: "ai",
      text: "Good question — this is a quadratic that factorises cleanly. Before I just hand over the answer:",
      offer: true,
    };
  }
  switch (mode.id) {
    case "exam":
      return {
        role: "ai",
        text: `Exam-style answer for "${userText}":\n\n• Definition first — state it in one precise line (that's usually 1 mark).\n• Key formula / law with symbols defined.\n• One labelled example or diagram description.\n\nIn a full build this response comes from the Mistral API, grounded in your class ${"10"} ${"CBSE"} syllabus. Want me to convert this into flashcards?`,
      };
    case "revision":
      return {
        role: "ai",
        text: `Rapid recap of "${userText}":\n\n1. Core idea in one sentence\n2. The 3 formulas examiners love\n3. The classic trap students fall into\n\nNow recall check — without looking, can you tell me point 1 in your own words?`,
      };
    case "challenge":
      return {
        role: "ai",
        text: `🔥 Challenge accepted. Here's a question one level above your grade on "${userText}". Take your time — I'll only give hints if you ask.\n\nQ: A two-digit number is 4 times the sum of its digits and twice the product of its digits. Find the number.\n\nWould you like a hint, or will you attempt it first?`,
        offer: true,
      };
    case "teach":
      return {
        role: "ai",
        text: `Let's build "${userText}" from zero. 🧑‍🏫\n\nImagine you're explaining it to a younger sibling — that's the level we'll start at, then climb. First, the everyday analogy… then the definition… then one worked example, and finally you teach it back to me (that's when it sticks).\n\nReady? Here's the analogy: think of it like organising your school bag — everything has a place and a reason…`,
      };
    default:
      return {
        role: "ai",
        text: `Great question about "${userText}"! Let me break it down simply, adapted to your grade level.\n\nThe key idea is to connect it to something you already know, then layer the new concept on top with an example. In the full product this answer is generated by the Mistral API with your learning style and weak areas in context.\n\nWould you like a hint towards the answer, or a full explanation?`,
        offer: true,
      };
  }
}

export default function Tutor() {
  const [mode, setMode] = useState<Mode>(aiModes[0]);
  const [messages, setMessages] = useState<Msg[]>([
    { role: "ai", text: aiModes[0].greeting },
  ]);
  const [input, setInput] = useState("");
  const [typing, setTyping] = useState(false);
  const endRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: "smooth", block: "end" });
  }, [messages, typing]);

  function switchMode(m: Mode) {
    setMode(m);
    setMessages((prev) => [...prev, { role: "ai", text: m.greeting }]);
  }

  function pushAi(msg: Msg) {
    setTyping(true);
    setTimeout(() => {
      setTyping(false);
      setMessages((prev) => [...prev, msg]);
    }, 900);
  }

  function send(text?: string) {
    const value = (text ?? input).trim();
    if (!value || typing) return;
    setInput("");
    setMessages((prev) => [...prev, { role: "user", text: value }]);
    pushAi(aiReply(mode, value));
  }

  function chooseOffer(kind: "hint" | "solution") {
    setMessages((prev) => prev.map((m) => ({ ...m, offer: false })));
    pushAi({ role: "ai", text: kind === "hint" ? DEMO_HINT : DEMO_SOLUTION });
  }

  return (
    <div className="mx-auto max-w-4xl flex flex-col h-[calc(100vh-8.5rem)] lg:h-[calc(100vh-7.5rem)]">
      {/* mode selector */}
      <div className="flex gap-2 overflow-x-auto pb-3 -mx-1 px-1">
        {aiModes.map((m) => (
          <button
            key={m.id}
            onClick={() => switchMode(m)}
            title={m.desc}
            className={`shrink-0 flex items-center gap-1.5 rounded-full border px-4 py-2 text-xs font-medium transition-all ${
              mode.id === m.id
                ? "border-accent/60 bg-accent/20 text-white shadow-[0_0_18px_-4px_rgba(139,92,246,0.6)]"
                : "border-edge bg-card text-sub hover:text-white hover:border-edge2"
            }`}
          >
            <span>{m.emoji}</span>
            {m.name}
          </button>
        ))}
      </div>

      {/* chat window */}
      <div className="card flex-1 min-h-0 flex flex-col overflow-hidden">
        <div className="flex items-center gap-2 border-b border-edge px-5 py-3 text-xs text-faint">
          <span className="size-2 rounded-full bg-mint animate-pulse-glow" />
          AI Tutor · {mode.name} · adapts to Class 10 CBSE
          <span className="ml-auto hidden sm:block">Memory: on</span>
        </div>

        <div className="flex-1 overflow-y-auto px-4 sm:px-6 py-5 space-y-4">
          {messages.map((m, i) => (
            <div key={i} className={`animate-fade-up ${m.role === "user" ? "flex justify-end" : ""}`}>
              <div
                className={`max-w-[88%] sm:max-w-[75%] whitespace-pre-wrap rounded-2xl px-4 py-3 text-sm leading-relaxed ${
                  m.role === "user"
                    ? "rounded-br-md bg-primary/25 border border-primary/35"
                    : "rounded-bl-md bg-card2 border border-edge"
                }`}
              >
                {m.text}
                {m.offer && (
                  <div className="mt-3 flex flex-wrap gap-2">
                    <button
                      onClick={() => chooseOffer("hint")}
                      className="rounded-full bg-accent/20 border border-accent/50 px-4 py-1.5 text-xs font-medium text-accent2 hover:bg-accent/30 transition-colors"
                    >
                      💡 Give me a hint
                    </button>
                    <button
                      onClick={() => chooseOffer("solution")}
                      className="rounded-full bg-white/5 border border-edge px-4 py-1.5 text-xs font-medium text-sub hover:text-white hover:border-edge2 transition-colors"
                    >
                      Show complete solution
                    </button>
                  </div>
                )}
              </div>
            </div>
          ))}
          {typing && (
            <div className="animate-fade-in">
              <div className="w-fit rounded-2xl rounded-bl-md bg-card2 border border-edge px-4 py-3 flex gap-1.5">
                {[0, 1, 2].map((i) => (
                  <span
                    key={i}
                    className="size-1.5 rounded-full bg-sub animate-pulse-glow"
                    style={{ animationDelay: `${i * 200}ms`, animationDuration: "1s" }}
                  />
                ))}
              </div>
            </div>
          )}
          <div ref={endRef} />
        </div>

        {/* composer */}
        <div className="border-t border-edge p-3 sm:p-4">
          <div className="flex gap-2 mb-2.5 overflow-x-auto">
            {["Solve: x² − 5x + 6 = 0", "Explain refraction with an analogy", "Quiz me on Ch. 3"].map((s) => (
              <button
                key={s}
                onClick={() => send(s)}
                className="shrink-0 rounded-full border border-edge bg-card2 px-3.5 py-1.5 text-[11px] text-sub hover:text-white hover:border-accent/40 transition-colors"
              >
                {s}
              </button>
            ))}
          </div>
          <form
            className="flex items-end gap-2"
            onSubmit={(e) => {
              e.preventDefault();
              send();
            }}
          >
            <textarea
              rows={1}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  send();
                }
              }}
              placeholder={`Ask in ${mode.name}…`}
              className="flex-1 resize-none rounded-xl border border-edge bg-ink/60 px-4 py-3 text-sm outline-none placeholder:text-faint focus:border-accent/60 focus:ring-2 focus:ring-accent/20 transition"
            />
            <button
              type="submit"
              aria-label="Send"
              className="btn-glow size-11 shrink-0 grid place-items-center rounded-xl"
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
                <path d="m5 12 14-7-4 14-3.5-5.5L5 12Z" stroke="#fff" strokeWidth="2" strokeLinejoin="round" />
              </svg>
            </button>
          </form>
          <div className="mt-2 text-center text-[10px] text-faint">
            Learning comes before answers — the tutor offers hints first.
          </div>
        </div>
      </div>
    </div>
  );
}
